title:             Asian Outreach Cambodia
email:             info@aocam.org
description: ""
author: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript
    
include: ["_pages"]

exclude:
  - LICENSE
  - README.md

# Social Profiles
twitter_username: ""
github_username: ""
facebook_username: ""
