title: "Asian Outreach Cambodia"
email: "info@aocam.org"
description: ""
author: ""

baseurl: ""
url: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

include: ["_pages"]

# Social Profiles
twitter_username: ""
github_username: ""
facebook_username: ""

exclude:
  - LICENSE
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon
  - docker-compose.yml

# Default Markdown Engine
markdown: kramdown

